version: "3"

services:
  mongodb:
    image: mongo
    environment:
      - MONGODB_DATABASE="mevn-tasks-app"
    ports:
      - '27017:27017'
    expose:
      - '27017'

  tasks-api:
    build: ./server
    environment:
      - NODE_ENV=production
      - DB_HOST=mongodb
    ports:
      - '3001:3001'
    links:
      - mongodb
    depends_on:
      - mongodb

  tasks-client:
    build: ./client
    environment:
      - NODE_ENV=production
    ports:
      - '8080:8080'
    links:
      - tasks-api
    depends_on:
      - tasks-api